load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "i_sort",
    hdrs = ["i_sort.h"],
    deps = [
        "//cyber",
    ],
)

cpplint()
