load("//tools/install:install.bzl", "install")

package(
    default_visibility = ["//visibility:public"],
)

install(
    name = "install",
    deps = [
        "//modules/common/data:install",
        "//modules/common/vehicle_model:install",
    ],
)
