load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "lane_follow_park_proto",
    srcs = ["lane_follow_park_scenario.proto"],
)

apollo_package()
