package(default_visibility = ["//visibility:public"])

filegroup(
    name = "config",
    srcs = [
        "offline_lidar_perception_test.flag",
        "offline_sequential_obstacle_perception_test.flag",
    ],
)
