package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "multi_camera_projection_config_lib_proto",
    deps = [
        ":multi_camera_projection_config_lib",
    ],
)

proto_library(
    name = "multi_camera_projection_config_lib",
    srcs = [
        "multi_camera_projection_config.proto",
    ],
)

cc_proto_library(
    name = "recognizer_config_lib_proto",
    deps = [
        ":recognizer_config_lib",
    ],
)

proto_library(
    name = "recognizer_config_lib",
    srcs = [
        "recognizer_config.proto",
    ],
)

cc_proto_library(
    name = "preprocessor_config_lib_proto",
    deps = [
        ":preprocessor_config_lib",
    ],
)

proto_library(
    name = "preprocessor_config_lib",
    srcs = [
        "preprocessor_config.proto",
    ],
)

cc_proto_library(
    name = "rectifier_config_lib_proto",
    deps = [
        ":rectifier_config_lib",
    ],
)

proto_library(
    name = "rectifier_config_lib",
    srcs = [
        "rectifier_config.proto",
    ],
)

cc_proto_library(
    name = "reviser_config_lib_proto",
    deps = [
        ":reviser_config_lib",
    ],
)

proto_library(
    name = "reviser_config_lib",
    srcs = [
        "reviser_config.proto",
    ],
)

cc_proto_library(
    name = "subnode_config_lib_proto",
    deps = [
        ":subnode_config_lib",
    ],
)

proto_library(
    name = "subnode_config_lib",
    srcs = [
        "subnode_config.proto",
    ],
)
