load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "lane_escape_proto",
    srcs = ["lane_escape_scenario.proto"],
)

apollo_package()
