/* eslint-disable prettier/prettier */
export type IImageName =
'Components'|
'camera_view_hover_illustrator'|
'console_hover_illustrator'|
'dashboard_hover_illustrator'|
'dreamview'|
'ic_add_desktop_shortcut'|
'ic_aiming_circle'|
'ic_default_page_no_data'|
'ic_empty_page_no_data'|
'ic_fail_to_load'|
'ic_personal_center_default'|
'icon_green_light'|
'icon_red_light'|
'icon_yellow_light'|
'image_Charts'|
'image_ambient_light'|
'loader_apollo'|
'menu_drawer_add_panel_hover'|
'module_delay_hover_illustrator'|
'panel_chart'|
'pointcloud_hover_illustrator'|
'terminal_Illustrator'|
'vehicle_viz_hover_illustrator'|
'view_login_step_first'|
'view_login_step_fourth'|
'view_login_step_second'|
'view_login_step_third_one'|
'view_login_step_third_two'|
'welcome_guide_background'|
'welcome_guide_decorate_ele'|
'welcome_guide_logo'|
'welcome_guide_logov2'|
'welcome_guide_tabs_image_default'|
'welcome_guide_tabs_image_perception'|
'welcome_guide_tabs_image_pnc'|
'welcome_guide_tabs_image_vehicle';
