package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "camero_proto",
    deps = [
        ":camero_proto_lib",
    ],
)

proto_library(
    name = "camero_proto_lib",
    srcs = [
        "camera_conf.proto",
    ],
)
