#!/usr/bin/env bash

###############################################################################
# Copyright 2020 The Apollo Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
# For development only! Will remove before merging to master!
# Testing steps:
# 1. Start container: ./docker/scripts/dev_start.sh
# 2. Login to container: ./docker/scripts/dev_into.sh
# 3. Run this script.
###############################################################################

cd "$( dirname "${BASH_SOURCE[0]}" )"
cp WORKSPACE.in WORKSPACE

# Fail on first failure.
set -e

# Working parts.
bazel build //cyber/...
bazel test //cyber/...
bazel build //modules/common/...
bazel test //modules/common/...
bazel build //modules/routing/...
bazel test //modules/routing/...
bazel build //modules/storytelling/...
bazel test //modules/storytelling/...
bazel build //modules/transform/...
bazel test //modules/transform/...
bazel build //modules/v2x/...
bazel test //modules/v2x/...
bazel build //modules/control/...
bazel test //modules/control/...
bazel build //modules/canbus/...
bazel test //modules/canbus/...
bazel build //modules/bridge/...
bazel test //modules/bridge/...

bazel build //modules/tools/...
# Note(storypku): bazel test works except some lint errors in cyber_visualizer.
# Will re-check if cyber_visualizer work correctly once it becomes stable
for entry in $(bazel query //modules/tools/... except //modules/tools/visualizer/...); do
    bazel test $entry
done

# TODO(storypku): Add grpc support in proto_build_generator.py

# In-progress parts. Feel free to claim by adding your name in TODO and move it
# above when you finish.

# TODO(?): bazel build //modules/contrib/...
# TODO(xiaoxq): bazel build //modules/data/...
# TODO(?): bazel build //modules/dreamview/...
# TODO(storypku): bazel build //modules/drivers/...
# TODO(storypku): bazel build //modules/guardian/...
# TODO(?): bazel build //modules/localization/...
# TODO(storypku): bazel build //modules/map/...
# TODO(storypku): bazel build //modules/monitor/...
# TODO(?): bazel build //modules/perception/...
# TODO(storypku): bazel build //modules/planning/...
# TODO(?): bazel build //modules/prediction/...
# TODO(?): bazel build //modules/third_party_perception/...
