#!/usr/bin/env bash

###############################################################################
# Copyright 2020 The Apollo Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
# For development only! Will remove before merging to master!
###############################################################################

cd "$( dirname "${BASH_SOURCE[0]}" )"
cp WORKSPACE.in WORKSPACE

# Working parts.
bazel build //cyber/...
bazel test //cyber/...
bazel build //modules/tools/...

# bazel test works except some lint errors in cyber_visualizer.
# IIRC, cyber_visualizer works well. Will re-check it when
# modules/tools/visualizer beomes stable
for entry in $(bazel query //modules/tools/... except //modules/tools/visualizer/...); do
    bazel test $entry
done

# In-progress parts. Feel free to claim by adding your name in TODO and move it
# above when you finish.

# TODO(?): bazel build //modules/bridge/...
# TODO(?): bazel build //modules/canbus/...
# TODO(?): bazel build //modules/common/...
# TODO(?): bazel build //modules/contrib/...
# TODO(?): bazel build //modules/control/...
# TODO(xiaoxq): bazel build //modules/data/...
# TODO(?): bazel build //modules/dreamview/...
# TODO(?): bazel build //modules/drivers/...
# TODO(?): bazel build //modules/guardian/...
# TODO(?): bazel build //modules/localization/...
# TODO(?): bazel build //modules/map/...
# TODO(?): bazel build //modules/monitor/...
# TODO(?): bazel build //modules/perception/...
# TODO(?): bazel build //modules/planning/...
# TODO(?): bazel build //modules/prediction/...
# TODO(?): bazel build //modules/routing/...
# TODO(?): bazel build //modules/storytelling/...
# TODO(?): bazel build //modules/third_party_perception/...
# TODO(?): bazel build //modules/transform/...
# TODO(?): bazel build //modules/v2x/...
