load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "crosswalk_proto",
    srcs = ["crosswalk.proto"],
)

apollo_package()