package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "cnnseg_proto",
    deps = [
        ":cnnseg_proto_lib",
    ],
)

proto_library(
    name = "cnnseg_proto_lib",
    srcs = [
        "cnnseg.proto",
    ],
)
