package(default_visibility = ["//visibility:public"])

cc_library(
    name = "platform_hw_log_module_lib",
    srcs = ["hw_log_module.cc"],
    hdrs = ["hw_log_module.h"],
    deps = [
        "//modules/monitor/common:platform_common_lib",
    ],
)
