load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hw_log_module",
    srcs = ["hw_log_module.cc"],
    hdrs = ["hw_log_module.h"],
    deps = [
        "//modules/monitor/common:log",
    ],
)

cpplint()
