load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "i_plane",
    hdrs = [
        "i_plane.h",
    ],
    deps = [
    ],
)

# cpplint()