load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "inner_component_messages",
    hdrs = ["inner_component_messages.h"],
)

cpplint()
