load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "curvature",
    srcs = ["curvature.py"],
)

py_library(
    name = "frame_count",
    srcs = ["frame_count.py"],
)

py_library(
    name = "lat_acceleration",
    srcs = ["lat_acceleration.py"],
)

py_library(
    name = "latency",
    srcs = ["latency.py"],
)

py_library(
    name = "lon_acceleration",
    srcs = ["lon_acceleration.py"],
)

py_library(
    name = "reference_line",
    srcs = ["reference_line.py"],
)
