load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

# cc_library(
#     name = "dummy_algorithms",
#     srcs = ["dummy_algorithms.cc"],
#     hdrs = ["dummy_algorithms.h"],
#     deps = [
#         "//modules/common:log",
#         "//modules/perception/obstacle/base:perception_obstacle_base",
#         "@caffe//:lib",
#         "@eigen",
#     ],
# )

cpplint()
