package(default_visibility = ["//visibility:public"])

filegroup(
    name = "lidar_ex_checker_adapter_manager_config",
    srcs = [
        "adapter.conf",
    ],
)

filegroup(
    name = "lidar_ex_checker_config",
    srcs = [
        "lidar_ex_checker.conf",
    ],
)
