load("//tools/proto:proto.bzl", "apollo_py_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

apollo_py_library(
    name = "chassis_data",
    srcs = ["chassis_data.py"],
)

apollo_py_library(
    name = "localization_data",
    srcs = ["localization_data.py"],
)

apollo_py_library(
    name = "mobileye_data",
    srcs = ["mobileye_data.py"],
)

apollo_py_library(
    name = "planning_data",
    srcs = ["planning_data.py"],
)

apollo_py_library(
    name = "routing_data",
    srcs = ["routing_data.py"],
)

apollo_py_library(
    name = "subplot_routing",
    srcs = ["subplot_routing.py"],
)

apollo_py_library(
    name = "subplot_s_speed",
    srcs = ["subplot_s_speed.py"],
)

apollo_py_library(
    name = "subplot_s_theta",
    srcs = ["subplot_s_theta.py"],
)

apollo_py_library(
    name = "subplot_s_time",
    srcs = ["subplot_s_time.py"],
)

apollo_py_library(
    name = "view_subplot",
    srcs = ["view_subplot.py"],
)

apollo_package()