load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "data_generator_gflags",
    srcs = [
        "data_generator_gflags.cc",
    ],
    hdrs = [
        "data_generator_gflags.h",
    ],
    deps = [
        "//external:gflags",
    ],
)

cpplint()
