package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "runtime_status_proto",
    deps = [":runtime_status_proto_lib"],
)

proto_library(
    name = "runtime_status_proto_lib",
    srcs = ["runtime_status.proto"],
)
