load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_inc_library(
    name = "interface",
    hdrs = [
        "hw_checker.h",
        "hw_status.h",
    ],
)

cpplint()
