load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "st_bounds_decider_proto",
    srcs = ["st_bounds_decider.proto"],
)

apollo_package()