/******************************************************************************
 * Copyright 2023 The Apollo Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

/**
 * @file
 * @brief Defines the DebugInfoControlTask class.
 */

#pragma once

#include <algorithm>
#include <memory>
#include <string>

#include "modules/common_msgs/config_msgs/vehicle_config.pb.h"
#include "modules/control/control_component/proto/control_debug.pb.h"

#include "cyber/cyber.h"
#include "cyber/plugin_manager/plugin_manager.h"
#include "modules/common/util/message_util.h"
#include "modules/control/control_task_base_extend/control_task_extend.h"
#include "modules/common/adapters/adapter_gflags.h"

/**
 * @namespace apollo::control
 * @brief apollo::control
 */
namespace apollo {
namespace control {

/**
 * @class DebugInfoControlTask
 *
 * @brief Publish the control debug msg.
 */
class DebugInfoControlTask : public ControlTaskExtend {
public:
    /**
     * @brief constructor
     */
    DebugInfoControlTask();

    /**
     * @brief destructor
     */
    virtual ~DebugInfoControlTask() = default;

    /**
     * @brief initialize DebugInfoControlTask
     * @return Status initialization status
     */
    common::Status Init(std::shared_ptr<DependencyInjector> injector) override;

    /**
     * @brief compute brake / throttle values based on current vehicle status
     *        and target trajectory
     * @param localization vehicle location
     * @param chassis vehicle status e.g., speed, acceleration
     * @param trajectory trajectory generated by planning
     * @param cmd control command
     * @return Status computation status
     */
    common::Status ComputeControlCommand(
            const localization::LocalizationEstimate *localization,
            const canbus::Chassis *chassis,
            const planning::ADCTrajectory *trajectory,
            control::ControlCommand *cmd) override;

    /**
     * @brief stop DebugInfoControlTask
     */
    void Stop() override;

    /**
     * @brief reset demo control task
     * @return Status reset status
     */
    common::Status Reset() override;

    /**
     * @brief DebugInfoControlTask name
     * @return string controller name in string
     */
    std::string Name() const override;

protected:
    std::shared_ptr<DependencyInjector> injector_;

private:
    void PublishDebugInfoThreadFunc();

private:
    std::unique_ptr<::apollo::cyber::Node> node_ = nullptr;
    std::shared_ptr<cyber::Writer<::apollo::control::ControlDebugInfo>> control_debug_info_writer_;
    std::string name_;

    ControlDebugInfo control_debug_info_msg_;
};

CYBER_PLUGIN_MANAGER_REGISTER_PLUGIN(apollo::control::DebugInfoControlTask, ControlTask)

}  // namespace control
}  // namespace apollo
