//
//  IAdapterMsgObserver.hpp
//  baiduNaviSDK
//
//  Created by griffin on 2016/10/28.
//  Copyright © 2016年 baidu. All rights reserved.
//

#ifndef IAdapterMsgObserver_hpp
#define IAdapterMsgObserver_hpp

#include <stdio.h>
#include "BNATools/navi_car_adapter_def.h"
#include "BNATools/navi_auto_guidance_def.h"
#include "BNATools/navi_auto_location_def.h"

NAMESPACE_BAIDU
NAMESPACE_BAIDU_ADAPTER

///////////////////////////////////////////Message Enum///////////////////////////////////////////


/** 逻辑层向上通知消息类型 */
typedef enum _BNANaviMessageTypeEnum
{
    BNA_NAVI_MESSAGE_TYPE_INVALID = 0x1000,                 /**<  Invalid */
    BNA_NAVI_MESSAGE_TYPE_LEVEL_CHANGED,                    /**<  Map Level Changed */
    BNA_NAVI_MESSAGE_TYPE_ROUTE_PLAN_RESULT_APP = 0x1003,
    BNA_NAVI_MESSAGE_TYPE_ROUTE_PLAN_RESULT = 0x1003+100,       /**<  Route Plan Result */
    BNA_NAVI_MESSAGE_TYPE_SIMPLE_GUIDANCE_INFO,
    BNA_NAVI_MESSAGE_TYPE_REMAIN_INFO = 0x1000+11,
    BNA_NAVI_MESSAGE_TYPE_HIGHWAY_INFO = 0x1000+52,
    BNA_NAVI_MESSAGE_TYPE_SPPED_LIMIT_INFO = 0x1000+124,
    BNA_NAVI_MESSAGE_TYPE_ASSIST_INFO = 0x1009,
    BNA_NAVI_MESSAGE_TYPE_POI_SEARCH_RESULT = 0x1021,       /**< POI Search */
    BNA_NAVI_MESSAGE_TYPE_POI_SEARCH_SUG_RESULT = 0x1022,       /**< POI Search */
    BNA_NAVI_MESSAGE_TYPE_POSITION_CHANGED = 0x1000+400,     /**< Map Position Changed */
    BNA_NAVI_MESSAGE_TYPE_SCREEN_SHOT = 0x3000     /**< Map Position Changed */
}BNANaviMessageTypeEnum;

//guide : msg for stub ;add by sfy
typedef enum _BNAGuideMessageTypeEnum
{
    //guidance info
    BNA_GUIDE_MESSAGE_TYPE_INVALID                       = 0x1000,
    BNA_GUIDE_MESSAGE_TYPE_NAVISTATUS_CHANGE = 0x1000+2,
    BNA_GUIDE_MESSAGE_TYPE_SIMPLEINFO= 0x1000+4,
    BNA_GUIDE_MESSAGE_TYPE_RASTEREXPANDMAP_SHOW,
    BNA_GUIDE_MESSAGE_TYPE_RASTEREXPANDMAP_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_RASTEREXPANDMAP_HIDE,
    BNA_GUIDE_MESSAGE_TYPE_ASSISTANTINFO_SHOW,
    BNA_GUIDE_MESSAGE_TYPE_ASSISTANTINFO_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_ASSISTANTINFO_HIDE,
    BNA_GUIDE_MESSAGE_TYPE_REMAININFO_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_ROADNAME_CHANGE,
    BNA_GUIDE_MESSAGE_TYPE_DIRECTBOARD_SHOW,
    BNA_GUIDE_MESSAGE_TYPE_DIRECTBOARD_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_DIRECTBOARD_HIDE,
    BNA_GUIDE_MESSAGE_TYPE_SIMPLEGUIDEINFO_HIDE = 0x1000+16,
    BNA_GUIDE_MESSAGE_TYPE_SIMPLEGUIDEINFO_SHOW,
    BNA_GUIDE_MESSAGE_TYPE_VECTOREXPANDMAP_SHOW = 0x1000+43,
    BNA_GUIDE_MESSAGE_TYPE_VECTOREXPANDMAP_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_VECTOREXPANDMAP_HIDE,
    BNA_GUIDE_MESSAGE_TYPE_MAINSLAVE_UPDTE,
    BNA_GUIDE_MESSAGE_TYPE_CRUISEYAW,
    BNA_GUIDE_MESSAGE_TYPE_MAINSLAVE_HIDEUPDTE,
    BNA_GUIDE_MESSAGE_TYPE_HIGHWAYINFO_SHOW = 0x1000+50,
    BNA_GUIDE_MESSAGE_TYPE_HIGHWAYINFO_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_HIGHWAYINFO_HIDE,
    BNA_GUIDE_MESSAGE_TYPE_POSTDESTPARKING = 0x1000+66,
    BNA_GUIDE_MESSAGE_TYPE_ONNAVIAVOIDROUTEMSG = 0x1000+73,
    BNA_GUIDE_MESSAGE_TYPE_SWITCHROUTE_SUCCESS = 0x1000+74,
    BNA_GUIDE_MESSAGE_TYPE_UPDATE_OTHER_ROUTE  = 0x1000+76,
    BNA_GUIDE_MESSAGE_TYPE_SWITCHROUTE_FAIL = 0x1000+77,
    BNA_GUIDE_MESSAGE_TYPE_UPDATEROADCONDITION = 0x1000+78,
    BNA_GUIDE_MESSAGE_TYPE_CHANGETOMAINROUTE = 0x1000+109,
    BNA_GUIDE_MESSAGE_TYPE_CHANGETOSLAVEROUTE,
    BNA_GUIDE_MESSAGE_TYPE_CHANGETOPARALLELROUTE,
    BNA_GUIDE_MESSAGE_TYPE_HIDECHANGEROUTE,
    BNA_GUIDE_MESSAGE_TYPE_SWITCHROUTE_START = 0x1000+304, /**< reroute plan(TODO:need modify engine)*/
    BNA_GUIDE_MESSAGE_TYPE_LANEINFO_SHOW = 0x1000+401, /**< lane info*/
    BNA_GUIDE_MESSAGE_TYPE_LANEINFO_UPDATE,
    BNA_GUIDE_MESSAGE_TYPE_LANEINFO_HIDE,
    BNA_GUIDE_MESSAGE_TYPE_YAWREROUTE,
    BNA_GUIDE_MESSAGE_TYPE_CANENTERCRUISE,
    BNA_GUIDE_MESSAGE_TYPE_SPEECHTEXT = 0x2000,  /**< speech text*/
    //adapter define
    BNA_LOCATION_MESSAGE_TYPE_TRIGGERGPSINFO, /**< location change*/
}BNAGuideMessageTypeEnum;


class IAdapterMsgObserver
{
public:
    
    IAdapterMsgObserver () {}
    virtual ~IAdapterMsgObserver () {}
    virtual bool Update (int unMsgID, int unArg1, void* nArg2) = 0 ;
};

NAMESPACE_END
NAMESPACE_END

#endif /* IAdapterMsgObserver_hpp */

