package(default_visibility = ["//visibility:public"])

cc_library(
    name = "perception_common",
    srcs = glob([
        "*.cc",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    deps = [
        "@glog//:glog",
    ],
)
