load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lane_follow",
    srcs = [
    ],
    hdrs = [
        "lane_follow_scenario.h",
    ],
    deps = [
        "//modules/common",
        "//modules/planning/common:planning_common",
    ],
)

cpplint()
