# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import collection_check_message_pb2 as collection__check__message__pb2


class CollectionCheckerServiceStub(object):
  """MAP
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DynamicAlign = channel.unary_unary(
        '/apollo.hdmap.CollectionCheckerService/DynamicAlign',
        request_serializer=collection__check__message__pb2.DynamicAlignRequest.SerializeToString,
        response_deserializer=collection__check__message__pb2.DynamicAlignResponse.FromString,
        )
    self.StaticAlign = channel.unary_unary(
        '/apollo.hdmap.CollectionCheckerService/StaticAlign',
        request_serializer=collection__check__message__pb2.StaticAlignRequest.SerializeToString,
        response_deserializer=collection__check__message__pb2.StaticAlignResponse.FromString,
        )
    self.EightRoute = channel.unary_unary(
        '/apollo.hdmap.CollectionCheckerService/EightRoute',
        request_serializer=collection__check__message__pb2.EightRouteRequest.SerializeToString,
        response_deserializer=collection__check__message__pb2.EightRouteResponse.FromString,
        )
    self.ChannelVerify = channel.unary_unary(
        '/apollo.hdmap.CollectionCheckerService/ChannelVerify',
        request_serializer=collection__check__message__pb2.ChannelVerifyRequest.SerializeToString,
        response_deserializer=collection__check__message__pb2.ChannelVerifyResponse.FromString,
        )
    self.LoopsVerify = channel.unary_unary(
        '/apollo.hdmap.CollectionCheckerService/LoopsVerify',
        request_serializer=collection__check__message__pb2.LoopsVerifyRequest.SerializeToString,
        response_deserializer=collection__check__message__pb2.LoopsVerifyResponse.FromString,
        )


class CollectionCheckerServiceServicer(object):
  """MAP
  """

  def DynamicAlign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StaticAlign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EightRoute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChannelVerify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoopsVerify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CollectionCheckerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DynamicAlign': grpc.unary_unary_rpc_method_handler(
          servicer.DynamicAlign,
          request_deserializer=collection__check__message__pb2.DynamicAlignRequest.FromString,
          response_serializer=collection__check__message__pb2.DynamicAlignResponse.SerializeToString,
      ),
      'StaticAlign': grpc.unary_unary_rpc_method_handler(
          servicer.StaticAlign,
          request_deserializer=collection__check__message__pb2.StaticAlignRequest.FromString,
          response_serializer=collection__check__message__pb2.StaticAlignResponse.SerializeToString,
      ),
      'EightRoute': grpc.unary_unary_rpc_method_handler(
          servicer.EightRoute,
          request_deserializer=collection__check__message__pb2.EightRouteRequest.FromString,
          response_serializer=collection__check__message__pb2.EightRouteResponse.SerializeToString,
      ),
      'ChannelVerify': grpc.unary_unary_rpc_method_handler(
          servicer.ChannelVerify,
          request_deserializer=collection__check__message__pb2.ChannelVerifyRequest.FromString,
          response_serializer=collection__check__message__pb2.ChannelVerifyResponse.SerializeToString,
      ),
      'LoopsVerify': grpc.unary_unary_rpc_method_handler(
          servicer.LoopsVerify,
          request_deserializer=collection__check__message__pb2.LoopsVerifyRequest.FromString,
          response_serializer=collection__check__message__pb2.LoopsVerifyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'apollo.hdmap.CollectionCheckerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
