# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collection_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import collection_check_message_pb2 as collection__check__message__pb2
import collection_data_message_pb2 as collection__data__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='collection_service.proto',
  package='apollo.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x63ollection_service.proto\x12\x0c\x61pollo.hdmap\x1a\x1e\x63ollection_check_message.proto\x1a\x1d\x63ollection_data_message.proto2\xce\x03\n\x18\x43ollectionCheckerService\x12W\n\x0c\x44ynamicAlign\x12!.apollo.hdmap.DynamicAlignRequest\x1a\".apollo.hdmap.DynamicAlignResponse\"\x00\x12T\n\x0bStaticAlign\x12 .apollo.hdmap.StaticAlignRequest\x1a!.apollo.hdmap.StaticAlignResponse\"\x00\x12Q\n\nEightRoute\x12\x1f.apollo.hdmap.EightRouteRequest\x1a .apollo.hdmap.EightRouteResponse\"\x00\x12Z\n\rChannelVerify\x12\".apollo.hdmap.ChannelVerifyRequest\x1a#.apollo.hdmap.ChannelVerifyResponse\"\x00\x12T\n\x0bLoopsVerify\x12 .apollo.hdmap.LoopsVerifyRequest\x1a!.apollo.hdmap.LoopsVerifyResponse\"\x00')
  ,
  dependencies=[collection__check__message__pb2.DESCRIPTOR,collection__data__message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COLLECTIONCHECKERSERVICE = _descriptor.ServiceDescriptor(
  name='CollectionCheckerService',
  full_name='apollo.hdmap.CollectionCheckerService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=106,
  serialized_end=568,
  methods=[
  _descriptor.MethodDescriptor(
    name='DynamicAlign',
    full_name='apollo.hdmap.CollectionCheckerService.DynamicAlign',
    index=0,
    containing_service=None,
    input_type=collection__check__message__pb2._DYNAMICALIGNREQUEST,
    output_type=collection__check__message__pb2._DYNAMICALIGNRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StaticAlign',
    full_name='apollo.hdmap.CollectionCheckerService.StaticAlign',
    index=1,
    containing_service=None,
    input_type=collection__check__message__pb2._STATICALIGNREQUEST,
    output_type=collection__check__message__pb2._STATICALIGNRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EightRoute',
    full_name='apollo.hdmap.CollectionCheckerService.EightRoute',
    index=2,
    containing_service=None,
    input_type=collection__check__message__pb2._EIGHTROUTEREQUEST,
    output_type=collection__check__message__pb2._EIGHTROUTERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChannelVerify',
    full_name='apollo.hdmap.CollectionCheckerService.ChannelVerify',
    index=3,
    containing_service=None,
    input_type=collection__check__message__pb2._CHANNELVERIFYREQUEST,
    output_type=collection__check__message__pb2._CHANNELVERIFYRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoopsVerify',
    full_name='apollo.hdmap.CollectionCheckerService.LoopsVerify',
    index=4,
    containing_service=None,
    input_type=collection__check__message__pb2._LOOPSVERIFYREQUEST,
    output_type=collection__check__message__pb2._LOOPSVERIFYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COLLECTIONCHECKERSERVICE)

DESCRIPTOR.services_by_name['CollectionCheckerService'] = _COLLECTIONCHECKERSERVICE

# @@protoc_insertion_point(module_scope)
