package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "cloud_node_conf_proto",
    deps = [
        ":cloud_node_conf_proto_lib",
    ],
)

proto_library(
    name = "cloud_node_conf_proto_lib",
    srcs = [
        "cloud_node_conf.proto",
    ],
)
