package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "velodyne_proto",
    deps = [
        ":velodyne_proto_lib",
    ],
)

proto_library(
    name = "velodyne_proto_lib",
    srcs = [
        "velodyne_conf.proto",
    ],
)
