package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "cloud_node_conf_proto",
    deps = [
        ":cloud_node_conf_proto_lib",
    ],
)

proto_library(
    name = "cloud_node_conf_proto_lib",
    srcs = [
        "cloud_node_conf.proto",
    ],
)

cc_proto_library(
    name = "transform_node_conf_proto",
    deps = [
        ":transform_node_conf_proto_lib",
    ],
)

proto_library(
    name = "transform_node_conf_proto_lib",
    srcs = [
        "transform_node_conf.proto",
    ],
)

cc_proto_library(
    name = "driver_node_conf_proto",
    deps = [
        ":driver_node_conf_proto_lib",
    ],
)

proto_library(
    name = "driver_node_conf_proto_lib",
    srcs = [
        "driver_node_conf.proto",
    ],
)
