load("//tools/install:install.bzl", "install", "install_files", "install_src_files")

package(default_visibility = ["//visibility:public"])


install(
    name = "conf_data", 
    data = [
        ":smart_recorder_config.pb.txt"
    ],
    data_dest = "data/addition_data/tools/smart_recorder/conf"
)