load("//tools/install:install.bzl", "install")

package(
    default_visibility = ["//visibility:public"],
)

install(
    name = "install",
    deps = [
        "//modules/drivers/camera:install",
    ],
)
