package(default_visibility = ["//visibility:public"])
load("//tools:apollo_package.bzl", "apollo_package")

filegroup(
    name = "testdata",
    srcs = glob([
        "*",
    ]),
)

apollo_package()