load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "relative_map_gflags",
    srcs = [
        "relative_map_gflags.cc",
    ],
    hdrs = [
        "relative_map_gflags.h",
    ],
    deps = [
        "//external:gflags",
    ],
)

cpplint()
