# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cyber_header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cyber_header.proto',
  package='cyber.proto',
  serialized_pb=_b('\n\x12\x63yber_header.proto\x12\x0f\x63yber.proto\"Q\n\x0b\x43yberHeader\x12\x12\n\nmeta_stamp\x18\x01 \x01(\x04\x12\r\n\x05stamp\x18\x02 \x01(\x04\x12\r\n\x05index\x18\x03 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CYBERHEADER = _descriptor.Descriptor(
  name='CyberHeader',
  full_name='cyber.proto.CyberHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta_stamp', full_name='cyber.proto.CyberHeader.meta_stamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='cyber.proto.CyberHeader.stamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='cyber.proto.CyberHeader.index', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='cyber.proto.CyberHeader.frame_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['CyberHeader'] = _CYBERHEADER

CyberHeader = _reflection.GeneratedProtocolMessageType('CyberHeader', (_message.Message,), dict(
  DESCRIPTOR = _CYBERHEADER,
  __module__ = 'cyber_header_pb2'
  # @@protoc_insertion_point(class_scope:cyber.proto.CyberHeader)
  ))
_sym_db.RegisterMessage(CyberHeader)


# @@protoc_insertion_point(module_scope)
