load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "converter_conf_proto",
    srcs = ["converter_conf.proto"],
)

proto_library(
    name = "ros_bridge_conf_proto",
    srcs = ["ros_bridge_conf.proto"],
)

apollo_package()