package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "cidiv2x_proto",
    deps = [
        ":cidiv2x_proto_lib",
    ],
)

proto_library(
    name = "cidiv2x_proto_lib",
    srcs = [
        "cidiv2x.proto",
    ],
    deps = [
        "//modules/common/proto:header_proto_lib",
    ],
)
