# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recorder_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recorder_info.proto',
  package='adu.eap.data_recorder',
  serialized_pb=_b('\n\x13recorder_info.proto\x12\x15\x61\x64u.eap.data_recorder\"\xff\x01\n\x0cRecorderInfo\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.adu.eap.data_recorder.StatusType\x12)\n\x04task\x18\x02 \x01(\x0b\x32\x1b.adu.eap.data_recorder.Task\x12\x31\n\x0cwriting_disk\x18\x03 \x01(\x0b\x32\x1b.adu.eap.data_recorder.Disk\x12)\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x1b.adu.eap.data_recorder.Data\x12\x33\n\tresources\x18\x05 \x01(\x0b\x32 .adu.eap.data_recorder.Resources\"6\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x10\n\x08\x64uration\x18\x03 \x01(\x01\"{\n\x04\x44isk\x12\n\n\x02sn\x18\x01 \x01(\t\x12\n\n\x02\x66s\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x01\x12\x0c\n\x04used\x18\x04 \x01(\x01\x12\r\n\x05\x61vail\x18\x05 \x01(\x01\x12\x13\n\x0buse_percent\x18\x06 \x01(\x01\x12\r\n\x05mount\x18\x07 \x01(\t\x12\x0c\n\x04slot\x18\x08 \x01(\t\"7\n\tResources\x12*\n\x05\x64isks\x18\x01 \x03(\x0b\x32\x1b.adu.eap.data_recorder.Disk\"0\n\x04\x44\x61ta\x12(\n\x04\x62\x61gs\x18\x01 \x03(\x0b\x32\x1a.adu.eap.data_recorder.Bag\"\x1f\n\x03\x42\x61g\x12\x18\n\x10writing_filename\x18\x01 \x01(\t*\xcc\x01\n\nStatusType\x12\x1b\n\x17OK_WAITING_FOR_COMMANDS\x10\x65\x12\x15\n\x11OK_RECORDING_DATA\x10\x66\x12\x19\n\x14\x41LERT_DISK_NOT_FOUND\x10\xc9\x01\x12\x19\n\x14\x41LERT_DISK_NOT_MOUNT\x10\xca\x01\x12\x1a\n\x15\x41LERT_DISK_IS_WARNING\x10\xcb\x01\x12\x18\n\x13\x41LERT_DISK_IS_FATAL\x10\xcc\x01\x12\x1e\n\x19\x41LERT_CTRLNODE_CONN_FAILE\x10\xcd\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='adu.eap.data_recorder.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK_WAITING_FOR_COMMANDS', index=0, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK_RECORDING_DATA', index=1, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_DISK_NOT_FOUND', index=2, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_DISK_NOT_MOUNT', index=3, number=202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_DISK_IS_WARNING', index=4, number=203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_DISK_IS_FATAL', index=5, number=204,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT_CTRLNODE_CONN_FAILE', index=6, number=205,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=626,
  serialized_end=830,
)
_sym_db.RegisterEnumDescriptor(_STATUSTYPE)

StatusType = enum_type_wrapper.EnumTypeWrapper(_STATUSTYPE)
OK_WAITING_FOR_COMMANDS = 101
OK_RECORDING_DATA = 102
ALERT_DISK_NOT_FOUND = 201
ALERT_DISK_NOT_MOUNT = 202
ALERT_DISK_IS_WARNING = 203
ALERT_DISK_IS_FATAL = 204
ALERT_CTRLNODE_CONN_FAILE = 205



_RECORDERINFO = _descriptor.Descriptor(
  name='RecorderInfo',
  full_name='adu.eap.data_recorder.RecorderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='adu.eap.data_recorder.RecorderInfo.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=101,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task', full_name='adu.eap.data_recorder.RecorderInfo.task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='writing_disk', full_name='adu.eap.data_recorder.RecorderInfo.writing_disk', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='adu.eap.data_recorder.RecorderInfo.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resources', full_name='adu.eap.data_recorder.RecorderInfo.resources', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=302,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='adu.eap.data_recorder.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='adu.eap.data_recorder.Task.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='adu.eap.data_recorder.Task.sequence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='adu.eap.data_recorder.Task.duration', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=358,
)


_DISK = _descriptor.Descriptor(
  name='Disk',
  full_name='adu.eap.data_recorder.Disk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='adu.eap.data_recorder.Disk.sn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fs', full_name='adu.eap.data_recorder.Disk.fs', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='adu.eap.data_recorder.Disk.size', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='used', full_name='adu.eap.data_recorder.Disk.used', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avail', full_name='adu.eap.data_recorder.Disk.avail', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_percent', full_name='adu.eap.data_recorder.Disk.use_percent', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mount', full_name='adu.eap.data_recorder.Disk.mount', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slot', full_name='adu.eap.data_recorder.Disk.slot', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=483,
)


_RESOURCES = _descriptor.Descriptor(
  name='Resources',
  full_name='adu.eap.data_recorder.Resources',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disks', full_name='adu.eap.data_recorder.Resources.disks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=540,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='adu.eap.data_recorder.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bags', full_name='adu.eap.data_recorder.Data.bags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=590,
)


_BAG = _descriptor.Descriptor(
  name='Bag',
  full_name='adu.eap.data_recorder.Bag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='writing_filename', full_name='adu.eap.data_recorder.Bag.writing_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=623,
)

_RECORDERINFO.fields_by_name['status'].enum_type = _STATUSTYPE
_RECORDERINFO.fields_by_name['task'].message_type = _TASK
_RECORDERINFO.fields_by_name['writing_disk'].message_type = _DISK
_RECORDERINFO.fields_by_name['data'].message_type = _DATA
_RECORDERINFO.fields_by_name['resources'].message_type = _RESOURCES
_RESOURCES.fields_by_name['disks'].message_type = _DISK
_DATA.fields_by_name['bags'].message_type = _BAG
DESCRIPTOR.message_types_by_name['RecorderInfo'] = _RECORDERINFO
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Disk'] = _DISK
DESCRIPTOR.message_types_by_name['Resources'] = _RESOURCES
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Bag'] = _BAG
DESCRIPTOR.enum_types_by_name['StatusType'] = _STATUSTYPE

RecorderInfo = _reflection.GeneratedProtocolMessageType('RecorderInfo', (_message.Message,), dict(
  DESCRIPTOR = _RECORDERINFO,
  __module__ = 'recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:adu.eap.data_recorder.RecorderInfo)
  ))
_sym_db.RegisterMessage(RecorderInfo)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:adu.eap.data_recorder.Task)
  ))
_sym_db.RegisterMessage(Task)

Disk = _reflection.GeneratedProtocolMessageType('Disk', (_message.Message,), dict(
  DESCRIPTOR = _DISK,
  __module__ = 'recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:adu.eap.data_recorder.Disk)
  ))
_sym_db.RegisterMessage(Disk)

Resources = _reflection.GeneratedProtocolMessageType('Resources', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCES,
  __module__ = 'recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:adu.eap.data_recorder.Resources)
  ))
_sym_db.RegisterMessage(Resources)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:adu.eap.data_recorder.Data)
  ))
_sym_db.RegisterMessage(Data)

Bag = _reflection.GeneratedProtocolMessageType('Bag', (_message.Message,), dict(
  DESCRIPTOR = _BAG,
  __module__ = 'recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:adu.eap.data_recorder.Bag)
  ))
_sym_db.RegisterMessage(Bag)


# @@protoc_insertion_point(module_scope)
