load("//tools/install:install.bzl", "install")

package(default_visibility = ["//visibility:public"])

install(
    name = "install",
    deps = [
        "//modules/drivers/radar/conti_radar:install",
        "//modules/drivers/radar/racobit_radar:install",
        "//modules/drivers/radar/ultrasonic_radar:install",
    ],
)
