package(default_visibility = ["//visibility:public"])

cc_library(
    name = "perception_obstacle_base",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//modules/perception/lib/pcl_util:pcl_util",
        "//modules/common:common",
        "@eigen//:eigen",
    ],
)

