load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "obj_split_proto",
    srcs = ["object_split_filter.proto"],
)

apollo_package()
