package(default_visibility = ["//visibility:public"])

filegroup(
    name = "perception_tool_config",
    srcs = [
        "config_manager.config",
        "offline_lidar_perception_test.flag",
    ],
)
