load("//tools:cpplint.bzl", "cpplint")

    package(default_visibility = ["//visibility:public"])

        cc_library(name = "perception_obstacle_camera_tracker_affinity_kcf",
                   srcs = [ "kcf_affinity_tracker.cc", "kcf_components.cc" ],
                   hdrs = [ "kcf_affinity_tracker.h", "kcf_components.h" ],
                   deps = [
#"@yaml_cpp//:yaml",
#"@eigen//:eigen",
#"@opencv2//:core",
#"//modules/perception/lib/base:base",
#"//modules/perception/lib/config_manager:config_manager",
#"//modules/perception/obstacle/camera/common:perception_obstacle_camera_common",
#"//modules/perception/obstacle/camera/interface:perception_obstacle_camera_interface"
])

            cpplint()
