## Auto generated by `proto_build_generator.py`
load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "%(car_type_lower)s_proto",
    srcs = ["%(car_type_lower)s.proto"],
)

apollo_package()
