load("//tools:apollo_package.bzl", "apollo_package")

package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "apollo_base",
    srcs = glob([
        "*.sh",
        "*.py",
        "*.txt",
    ]),
)

apollo_package()