export const ADD_SELECTED_PANEL_ID = 'ADD_SELECTED_PANEL_ID';
export const DELETE_SELECTED_PANEL_ID = 'DELETE_SELECTED_PANEL_ID';
export const ADD_KEY_HANDLER = 'ADD_KEY_HANDLER';
export const ADD_GLOABLE_KEY_HANDLER = 'ADD_GLOABLE_KEY_HANDLER';
export const REMOVE_KEY_HANDLER = 'REMOVE_KEY_HANDLER';
export const REMOVE_GLOABLE_KEY_HANDLER = 'REMOVE_GLOABLE_KEY_HANDLER';
