load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "park_and_go_proto",
    srcs = ["park_and_go.proto"],
)

apollo_package()