package(default_visibility = ["//visibility:public"])

filegroup(
    name = "perception_adapter_manager_config",
    srcs = [
        "adapter.conf",
    ],
)

filegroup(
    name = "perception_config",
    srcs = [
        "config_manager.config",
        "dag_streaming.config",
        "perception.conf",
    ],
)
