package(default_visibility = ["//visibility:public"])

cc_library(
    name = "perception_algorithm_dummy",
    srcs = [
        "dummy_algorithms.cc"
    ],
    hdrs = [
        "dummy_algorithms.h"
    ],
    deps = [
        "//modules/common:log",
        "//modules/perception/obstacle/lidar/interface:interface",
        "//modules/perception/obstacle/common:common",
        "@pcl//:pcl",
        "@eigen//:eigen",
    ],
)
