// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/task_manager/proto/

#include "modules/task_manager/proto/.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_modules_2ftask_5fmanager_2fproto_2f = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_modules_2ftask_5fmanager_2fproto_2f = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_modules_2ftask_5fmanager_2fproto_2f = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_modules_2ftask_5fmanager_2fproto_2f::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_modules_2ftask_5fmanager_2fproto_2f[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033modules/task_manager/proto/"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_modules_2ftask_5fmanager_2fproto_2f_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_modules_2ftask_5fmanager_2fproto_2f_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_modules_2ftask_5fmanager_2fproto_2f_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2ftask_5fmanager_2fproto_2f = {
  false, false, descriptor_table_protodef_modules_2ftask_5fmanager_2fproto_2f, "modules/task_manager/proto/", 29,
  &descriptor_table_modules_2ftask_5fmanager_2fproto_2f_once, descriptor_table_modules_2ftask_5fmanager_2fproto_2f_sccs, descriptor_table_modules_2ftask_5fmanager_2fproto_2f_deps, 0, 0,
  schemas, file_default_instances, TableStruct_modules_2ftask_5fmanager_2fproto_2f::offsets,
  file_level_metadata_modules_2ftask_5fmanager_2fproto_2f, 0, file_level_enum_descriptors_modules_2ftask_5fmanager_2fproto_2f, file_level_service_descriptors_modules_2ftask_5fmanager_2fproto_2f,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_modules_2ftask_5fmanager_2fproto_2f = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_modules_2ftask_5fmanager_2fproto_2f)), true);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
