package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dreamview_adapter_manager_config",
    srcs = [
        "adapter.conf",
    ],
)

filegroup(
    name = "hmi_config",
    srcs = [
        "hmi.conf",
    ],
)
