load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "diff_drive_lat_controller_conf_proto",
    srcs = ["diff_drive_lat_controller_conf.proto"],
)

apollo_package()
