load("//tools/install:install.bzl", "install", "install_src_files")

package(default_visibility = ["//visibility:public"])

install(
    name = "install",
    deps = [
        "//modules/canbus_vehicle/ch:install",
        "//modules/canbus_vehicle/devkit:install",
        "//modules/canbus_vehicle/ge3:install",
        "//modules/canbus_vehicle/gem:install",
        "//modules/canbus_vehicle/lexus:install",
        "//modules/canbus_vehicle/lincoln:install",
        "//modules/canbus_vehicle/neolix_edu:install",
        "//modules/canbus_vehicle/transit:install",
        "//modules/canbus_vehicle/wey:install",
        "//modules/canbus_vehicle/zhongyun:install",
    ],
)

install_src_files(
    name = "install_src",
    deps = [
        "//modules/canbus_vehicle/ch:install_src",
        "//modules/canbus_vehicle/devkit:install_src",
        "//modules/canbus_vehicle/ge3:install_src",
        "//modules/canbus_vehicle/gem:install_src",
        "//modules/canbus_vehicle/lexus:install_src",
        "//modules/canbus_vehicle/lincoln:install_src",
        "//modules/canbus_vehicle/neolix_edu:install_src",
        "//modules/canbus_vehicle/transit:install_src",
        "//modules/canbus_vehicle/wey:install_src",
        "//modules/canbus_vehicle/zhongyun:install_src",
    ],
)
