load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])


py_binary(
    name = "bound",
    srcs = ["bound.py"],
    deps = [
       
    ],
)


