load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bridge_gflags",
    srcs = [
        "bridge_gflags.cc",
    ],
    hdrs = [
        "bridge_gflags.h",
    ],
    deps = [
    ],
)


cpplint()
