package(default_visibility = ["//visibility:public"])

cc_library(
    name = "interface",
    srcs = [],
    hdrs = glob(["*.h"]),
    deps = [
        "//modules/perception/lib/pcl_util:pcl_util",
        "//modules/perception/lib/base:base",
        "//modules/perception/obstacle/base:perception_obstacle_base",
    ]
)
