package(default_visibility = ["//visibility:public"])

py_binary(
    name = "record",
    srcs = ["record.py"],
    deps = [
        "//cyber/proto:unit_test_pb2",
        "//cyber/python/cyber_py3:record",
        "//modules/common/util/testdata:simple_pb2",
    ],
)
