load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "pcl_method_proto",
    srcs = ["pcl_method.proto"],
)

apollo_package()
